### ISSUE TITLE
Does it work with foreground, foreground mask, and background images?

### ISSUE THREAD

**Issue by MianWang123** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#10]
Hi, there. Great job extending [Object-Shadow-Generation-Dataset-DESOBA]. Here's the situation, I got the foreground image, foreground mask, background image, can i use your method to generate shadow as it's realized in [Object-Shadow-Generation-Dataset-DESOBA]?

**Comment by MianWang123** [comment]
I tried to fill the rest folders (e.g. background_object_masks, background_shadow_masks) with black images, the model ran successfully, only the output looked weird.

**Comment by Narumi-Maria** [comment]
If the scenes in your data are significantly different, you may need to retrain in your domain. For example, the results we generated for indoor scenes were not good.

**Comment by MianWang123** [comment]
> If the scenes in your data are significantly different, you may need to retrain in your domain. For example, the results we generated for indoor scenes were not good.

Just wanna make sure, "fg img + fg mask + bg img" are enough for the inputs, or these inputs are suitable for ur model
