### ISSUE TITLE
[ Urgent Issue ] HR_desobav2 Data set is severely duplicated

### ISSUE THREAD

**Issue by igodogi** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#11]
Thanks for your great work. 
But as shown in the figure, HR_desobav2 may have been polluted, while desobav2-256x256.rar is correct. 
![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/aebc9442-dbb0-4880-850f-d862a4b9fb89)

Could you please upload a correct copy again for HR_desobav2? We need it for making HR training dataset.

**Comment by Narumi-Maria** [comment]
We have downloaded and checked the file, and we did not find any damage or duplicates. Please ensure that the size of the downloaded file matches the size displayed on the cloud drive.

**Comment by igodogi** [comment]
Thanks for the quick reply, I checked the file size. It is not caused by downloading the file.
The md5 code on my side is as follows:
![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/162abd21-94f7-479b-af2a-4f67ad715ee5)

I mean, there is a problem with the high-resolution version, that is, **desobav2.rar in BaiduCloud** and **hr.rar in OneDrive**, **not the “desobav2-256x256.rar”**.  Is this the file you're checking?

**Comment by Narumi-Maria** [comment]
> Thanks for the quick reply, I checked the file size. It is not caused by downloading the file.
> The md5 code on my side is as follows:
> ![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/162abd21-94f7-479b-af2a-4f67ad715ee5)
> 
> I mean, there is a problem with the high-resolution version, that is, **desobav2.rar in BaiduCloud** and **hr.rar in OneDrive**, **not the “desobav2-256x256.rar”**.  Is this the file you're checking?

I'm sure I checked the high-resolution version. You can try downloading it again.

**Comment by Narumi-Maria** [comment]
> Thanks for the quick reply, I checked the file size. It is not caused by downloading the file.
> The md5 code on my side is as follows:
> ![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/162abd21-94f7-479b-af2a-4f67ad715ee5)
> 
> I mean, there is a problem with the high-resolution version, that is, **desobav2.rar in BaiduCloud** and **hr.rar in OneDrive**, **not the “desobav2-256x256.rar”**.  Is this the file you're checking?

btw you can also check for any errors during the extraction process.

**Comment by igodogi** [comment]
The **hr.rar** was re-downloaded from another disk.  I compared those tow .rar with MD5, and they are consistent.  So, I don't think it's my download error.
Can you check your MD5?  Is my MD5 wrong with your MD5?
 

BTW, there are a lot of pics in the .rar file with CRC and bytes, of course without any extraction errors. 
We can see again:
![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/fad7d9cb-65f5-4028-b486-a471267a3b13)

**Comment by Narumi-Maria** [comment]
> The **hr.rar** was re-downloaded from another disk.  I compared those tow .rar with MD5, and they are consistent.  So, I don't think it's my download error.
> Can you check your MD5?  Is my MD5 wrong with your MD5?
>  
> 
> BTW, there are a lot of pics in the .rar file with **same** CRC and bytes, of course without any extraction errors. 
> We can see again:
> ![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/26406574/fad7d9cb-65f5-4028-b486-a471267a3b13)

Did you download it from Baidu Cloud?

**Comment by igodogi** [comment]
desobav2.rar from BaiduCloud 
hr.rar from OneDrive

**Comment by igodogi** [comment]
> Thanks for the quick reply, I checked the file size. It is not caused by downloading the file. The md5 code on my side is as follows: ![image](https://private-user-images.githubusercontent.com/26406574/344141625-162abd21-94f7-479b-af2a-4f67ad715ee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODE4MDQsIm5iZiI6MTcxOTU4MTUwNCwicGF0aCI6Ii8yNjQwNjU3NC8zNDQxNDE2MjUtMTYyYWJkMjEtOTRmNy00NzliLWFmMmEtNGY2N2FkNzE1ZWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEzMzE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTQyZTM4OWU4MmVlNWFkMDFjNjIwMmZiYTdkNWE5MTZiMjgxMzY4N2YzMzkxMmQ3MzY2MDQyOGM4ZjYxNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZ4aNs5X2QQbkCEqs5zdTOZsIMzJzI7Rz0OoBYxDHcM)
> 
> I mean, there is a problem with the high-resolution version, that is, **desobav2.rar in BaiduCloud** and **hr.rar in OneDrive**, **not the “desobav2-256x256.rar”**. Is this the file you're checking?

----------------------------------------------------------------------------------------------------
**desobav2.rar** from BaiduCloud 
**hr.rar** from OneDrive
They are the totally same wrong, as md5 are same.

**Comment by igodogi** [comment]
@Narumi-Maria Hello bro, any good news?

**Comment by Narumi-Maria** [comment]
> @Narumi-Maria Hello, any good news?

After inspection, our data is fine. You can add my WeChat 13079827921, and I will check if there are any issues with your decompression.
