### ISSUE TITLE
duplicate images in dataset

### ISSUE THREAD

**Issue by yongsuH** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#13]
First let me thank you for your great work!

I downloaded the high-res version of your dataset and found that this image below shows up in the dataset for thousands of times with masks seem identical to me. Is there any specific reason for doing so? I trained a shadow removal model and found it overfitting on this image.

![14821_0](https://github.com/user-attachments/assets/99aa7c44-d182-4164-b12d-9f6bb9424f79)

**Comment by ustcnewly** [comment]
Thanks for your feedback. We have updated the OneDrive link.
