### ISSUE TITLE
Will the pipeline codes for datasets construction be opened?

### ISSUE THREAD

**Issue by igodogi** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#2]

**Comment by Narumi-Maria** [comment]
The code for constructing the dataset is not yet organized. If you need it urgently, please leave your email, and I can send you the unorganized version.

**Comment by dorianzhang7** [comment]
Hello, auther. I recently came across your remarkable work and I want to extend dataset, Could you send me the code of dataset construction? (email: zhangdorian7@gmail.com).
Thank you very much for considering my request！
