### ISSUE TITLE
libcom.shadow_generation

### ISSUE THREAD

**Issue by Echo411** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#3]
您好！我在libcom.shadow_generation这个接口中发现调用的还是以前的阴影生成模型，是还没有更新为SGDiffusion吗？
![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/60573292/54d007db-e00b-4a66-b6e2-d61879918aec)

期待您的回复！

**Comment by Narumi-Maria** [comment]
There are no updates at the moment; you can directly use the model from this repository for testing.
