### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Echo411** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#4]
Hello, I downloaded the model weight from the link you gave, but it could not be loaded during the running process. The error message is: **PytorchStreamReader failed reading zip archive: failed finding central directory**
The specific error is as follows:
![image](https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2/assets/60573292/eda9ea3e-2268-4879-bd7d-d05dfebf3b63)

**Comment by Narumi-Maria** [comment]
Please unzip the downloaded file before loading it.

**Comment by Jidkboh** [comment]
> Please unzip the downloaded file before loading it.

I have the same problem ,I mean the file is not a zipped file ,it's ".pth"

**Comment by Narumi-Maria** [comment]
> > Please unzip the downloaded file before loading it.
> 
> I have the same problem ,I mean the file is not a zipped file ,it's ".pth"


After my verification, the files in the cloud drive are not damaged. However, you might encounter this issue when your file download is interrupted. Please ensure that the file size on your local device matches the size displayed on the cloud drive.
