### ISSUE TITLE
Request the code of dataset construction

### ISSUE THREAD

**Issue by dorianzhang7** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#6]
Hello, author. I recently came across your remarkable work and want to extend the dataset, Could you send me the code of the dataset construction? (email: [zhangdorian7@gmail.com](mailto:zhangdorian7@gmail.com)).
Thank you very much for considering my request！

**Comment by Narumi-Maria** [comment]
It has already been sent to your email.

**Comment by chl916185** [comment]
@Narumi-Maria 
Could you send me the code of the dataset construction? (email: [chenhongzijing@163.com).
Thank you very much for considering my request！
