### ISSUE TITLE
Questions about model parameter initialization

### ISSUE THREAD

**Issue by dorianzhang7** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#7]
Hello.
This work is based on the ControlNet method. The structure diagram of the paper shows that the parameters of UNet in the model are frozen. I would like to know how the parameters of UNet are initialized. Can you send me parameters or links if it is a pre-trained model?
Thanks for your reply!

**Comment by Narumi-Maria** [comment]
We freeze parameter settings consistent with Controlnet; you can refer to https://github.com/lllyasviel/ControlNet.
