### ISSUE TITLE
ckpt issue

### ISSUE THREAD

**Issue by yuhaoliu7456** [bcmi/Object-Shadow-Generation-Dataset-DESOBAv2#9]
Great work. I would like to know the difference between the DESOBAv2.ckpt and the other weights, e.g., mask_predictor and Net_best. I found that the state_dict of the DESOBAv2.ckpt already contains the keys of mask_predictor and scale_encoder. Another issue is that if I want to train this method from scratch, should I save just one DESOBAv2.ckpt or all weights? Sadly, I did not find the code to save mask_predictor and Net_best. Hope to hear from you soon.

Thanks

**Comment by Narumi-Maria** [comment]
> Great work. I would like to know the difference between the DESOBAv2.ckpt and the other weights, e.g., mask_predictor and Net_best. I found that the state_dict of the DESOBAv2.ckpt already contains the keys of mask_predictor and scale_encoder. Another issue is that if I want to train this method from scratch, should I save just one DESOBAv2.ckpt or all weights? Sadly, I did not find the code to save mask_predictor and Net_best. Hope to hear from you soon.
> 
> Thanks

You can use a global search to see which modules these weights correspond to. PyTorch provides an easy way to save the corresponding structure using torch.save(model.state_dict(), 'XXX_weights.pth')
